### ISSUE TITLE
mrepair  manquant

### ISSUE THREAD

**Issue by Pascal66** [axelroques/GIMTS#1]
https://github.com/axelroques/GIMTS/blob/e2853f8bc8e30fdac6f714aab7c4395f759f0393/gimts/gimts.py#L4

**Comment by axelroques** [comment]
Requirements and details on how the algorithm works can be found in the readme file.
You can find MRePair in another one of my repositories ([here](https://github.com/axelroques/M-RePair)).
You will also need the SAX algorithm, which you can also find in another one of my repositories ([here](https://github.com/axelroques/SAX)).

**Comment by Pascal66** [comment]
J'ai compris après coup qu'il fallait mettre tout les notebook au même endroit pour simplifier la vie.
Merci
Ca me permet de les tester tous
